name: Automatic Test Execution
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Mock a test
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "Before SHA: ${{ github.event.before.sha }}"
          echo "After SHA: ${{ github.event.after.sha }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}}"
